version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: help_sql
    environment:
      SA_PASSWORD: "StrongPassword@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

  api:
    build: .
    container_name: help_api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=HelpEmpowerment;User Id=sa;Password=StrongPassword@123;TrustServerCertificate=True"
    ports:
      - "5000:8080"
    networks:
      - app-network
    restart: always
    # ربط الكود مباشرة من السيرفر عشان Hot Reload ممكن يشتغل لو حبيت
    volumes:
      - ./HelpEmpowermentApi:/app
    command: >
      sh -c "dotnet restore && dotnet build && dotnet HelpEmpowermentApi.dll"

  help_frontend:
    build:
      context: /root/HelpEmpowermentUi
      dockerfile: Dockerfile
    container_name: help_frontend
    ports:
      - "8082:4000"
    networks:
      - app-network
    restart: always

volumes:
  sql_data:
