version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:  
      - help-network
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  help_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: help_api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HelpEmpowerment;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False;

    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - help-network
    restart: unless-stopped

  help_frontend:
    build:
      context: /root/HelpEmpowermentUi
      dockerfile: Dockerfile
    container_name: help_frontend
    ports:
      - "8082:4000"
    networks:
      - help-network
    restart: always
    depends_on:
      - help_api

networks:
  help-network:
    driver: bridge

volumes:
  sqldata:
