version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    networks:  
      - help-network
    volumes:
      - sqldata:/var/opt/mssql

  help_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: help_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HelpEmpowerment;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - help-network
  help_frontend:
    build:
      context: /root/HelpEmpowermentUi
      dockerfile: Dockerfile
    container_name: help_frontend
    ports:
      - "8082:4000"
    networks:
      - help-network
    restart: always
networks:
  help-network:
    driver: bridge

volumes:
  sqldata:
